// <auto-generated />
namespace WarOfEmpires.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AttacksIsRead : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AttacksIsRead));
        
        string IMigrationMetadata.Id
        {
            get { return "201912161642508_Attacks-IsRead"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
