// <auto-generated />
namespace WarOfEmpires.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PlayersBankedResources : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlayersBankedResources));
        
        string IMigrationMetadata.Id
        {
            get { return "201912271846429_Players-BankedResources"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
