// <auto-generated />
namespace WarOfEmpires.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class PlayersStamina : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PlayersStamina));
        
        string IMigrationMetadata.Id
        {
            get { return "201912101053396_Players-Stamina"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
