// <auto-generated />
namespace WarOfEmpires.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AuditingElapsedMilliseconds : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AuditingElapsedMilliseconds));
        
        string IMigrationMetadata.Id
        {
            get { return "202004191304424_Auditing-ElapsedMilliseconds"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
