// <auto-generated />
namespace WarOfEmpires.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class UserLastOnline : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UserLastOnline));
        
        string IMigrationMetadata.Id
        {
            get { return "202005311607264_User-LastOnline"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
