// <auto-generated />
namespace WarOfEmpires.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EmpiresWorkerTypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmpiresWorkerTypes));
        
        string IMigrationMetadata.Id
        {
            get { return "202002271330556_Empires-WorkerTypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
