// <auto-generated />
namespace WarOfEmpires.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class RoleAllianceRequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RoleAllianceRequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202009201607389_Role-Alliance-Required"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
