// <auto-generated />
namespace WarOfEmpires.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RolesCanManageNonAggressionPacts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RolesCanManageNonAggressionPacts));
        
        string IMigrationMetadata.Id
        {
            get { return "202102131437225_Roles-CanManageNonAggressionPacts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
