// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WarOfEmpires.Database;

namespace WarOfEmpires.Database.Migrations
{
    [DbContext(typeof(WarContext))]
    [Migration("20210715180825_Players-Blocks")]
    partial class PlayersBlocks
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.6")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AllianceNonAggressionPacts", b =>
                {
                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<int>("NonAggressionPactId")
                        .HasColumnType("int");

                    b.HasKey("AllianceId", "NonAggressionPactId");

                    b.HasIndex("NonAggressionPactId");

                    b.ToTable("AllianceNonAggressionPacts", "Alliances");
                });

            modelBuilder.Entity("AllianceWars", b =>
                {
                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<int>("WarId")
                        .HasColumnType("int");

                    b.HasKey("AllianceId", "WarId");

                    b.HasIndex("WarId");

                    b.ToTable("AllianceWars", "Alliances");
                });

            modelBuilder.Entity("PeaceDeclarations", b =>
                {
                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<int>("WarId")
                        .HasColumnType("int");

                    b.HasKey("AllianceId", "WarId");

                    b.HasIndex("WarId");

                    b.ToTable("PeaceDeclarations", "Alliances");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.AttackResultEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AttackResults", "Attacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Undefined"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Won"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Defended"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Surrendered"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Fatigued"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.AttackTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AttackTypes", "Attacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Raid"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Assault"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Grand overlord attack"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Revenge"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.BuildingTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BuildingTypes", "Empires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Farm"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Lumberyard"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Quarry"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Mine"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Forge"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Armoury"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Archery range"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Cavalry range"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Footman range"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Defences"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Huts"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Barracks"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Gold bank"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Food bank"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Wood bank"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Stone bank"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Ore bank"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Siege factory"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Market"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.GamePhaseEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GamePhases", "Game");

                    b.HasData(
                        new
                        {
                            Id = 0,
                            Name = "Truce"
                        },
                        new
                        {
                            Id = 1,
                            Name = "Active"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Finished"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.MerchandiseTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("MerchandiseTypes", "Markets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wood"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stone"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ore"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.SiegeWeaponTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SiegeWeaponTypes", "Siege");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Fire arrows"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Battering rams"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Scaling ladders"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.TaskExecutionModeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TaskExecutionModes", "Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Execute once"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Execute all intervals"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.TitleTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TitleTypes", "Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Peasant leader"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bandit leader"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Warband leader"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sub chieftain"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Chief"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Warlord"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Baron"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Viscount"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Earl"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Marquis"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Duke"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Prince"
                        },
                        new
                        {
                            Id = 13,
                            Name = "King"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Emperor"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Overlord"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Grand overlord"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.TroopTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TroopTypes", "Attacks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Archers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cavalry"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Footmen"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.UserEventTypeEntity", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserEventTypes", "Security");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "Logged in"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Failed log in"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Registered"
                        },
                        new
                        {
                            Id = (byte)4,
                            Name = "Activated"
                        },
                        new
                        {
                            Id = (byte)5,
                            Name = "Failed activation"
                        },
                        new
                        {
                            Id = (byte)6,
                            Name = "Activation code sent"
                        },
                        new
                        {
                            Id = (byte)7,
                            Name = "Logged out"
                        },
                        new
                        {
                            Id = (byte)8,
                            Name = "Password changed"
                        },
                        new
                        {
                            Id = (byte)9,
                            Name = "Failed password change"
                        },
                        new
                        {
                            Id = (byte)10,
                            Name = "Password reset requested"
                        },
                        new
                        {
                            Id = (byte)11,
                            Name = "Password reset"
                        },
                        new
                        {
                            Id = (byte)12,
                            Name = "Failed password reset"
                        },
                        new
                        {
                            Id = (byte)13,
                            Name = "Deactivated"
                        },
                        new
                        {
                            Id = (byte)14,
                            Name = "Failed deactivation"
                        },
                        new
                        {
                            Id = (byte)15,
                            Name = "Email change requested"
                        },
                        new
                        {
                            Id = (byte)16,
                            Name = "Failed email change request"
                        },
                        new
                        {
                            Id = (byte)17,
                            Name = "Email changed"
                        },
                        new
                        {
                            Id = (byte)18,
                            Name = "Failed email change"
                        },
                        new
                        {
                            Id = (byte)19,
                            Name = "Failed password reset request"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.UserStatusEntity", b =>
                {
                    b.Property<byte>("Id")
                        .HasColumnType("tinyint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserStatus", "Security");

                    b.HasData(
                        new
                        {
                            Id = (byte)1,
                            Name = "New"
                        },
                        new
                        {
                            Id = (byte)2,
                            Name = "Active"
                        },
                        new
                        {
                            Id = (byte)3,
                            Name = "Inactive"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.WorkerTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkerTypes", "Empires");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Farmers"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Wood workers"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Stone masons"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ore miners"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Siege engineers"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Merchants"
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.Alliance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int>("LeaderId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LeaderId");

                    b.ToTable("Alliances", "Alliances");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.ChatMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("ChatMessages", "Alliances");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.Invite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("PlayerId");

                    b.ToTable("Invites", "Alliances");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.NonAggressionPact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("NonAggressionPacts", "Alliances");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.NonAggressionPactRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("NonAggressionPactRequests", "Alliances");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AllianceId")
                        .HasColumnType("int");

                    b.Property<bool>("CanDeleteChatMessages")
                        .HasColumnType("bit");

                    b.Property<bool>("CanInvite")
                        .HasColumnType("bit");

                    b.Property<bool>("CanKickMembers")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageNonAggressionPacts")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageRoles")
                        .HasColumnType("bit");

                    b.Property<bool>("CanManageWars")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.ToTable("Roles", "Alliances");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.War", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.HasKey("Id");

                    b.ToTable("Wars", "Alliances");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Attack", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AttackType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AttackerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("DefenderId")
                        .HasColumnType("int");

                    b.Property<bool>("HasWarDamage")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAtWar")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("Result")
                        .HasColumnType("int");

                    b.Property<int>("Turns")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttackerId");

                    b.HasIndex("DefenderId");

                    b.HasIndex("Result");

                    b.HasIndex("Type");

                    b.ToTable("Attacks", "Attacks");

                    b.HasDiscriminator<string>("AttackType").HasValue("Attack");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.AttackRound", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackId")
                        .HasColumnType("int");

                    b.Property<long>("Damage")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsAggressor")
                        .HasColumnType("bit");

                    b.Property<int>("TroopType")
                        .HasColumnType("int");

                    b.Property<int>("Troops")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttackId");

                    b.HasIndex("TroopType");

                    b.ToTable("AttackRounds", "Attacks");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Casualties", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AttackRoundId")
                        .HasColumnType("int");

                    b.Property<int>("Mercenaries")
                        .HasColumnType("int");

                    b.Property<int>("Soldiers")
                        .HasColumnType("int");

                    b.Property<int>("TroopType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AttackRoundId");

                    b.HasIndex("TroopType");

                    b.ToTable("Casualties", "Attacks");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Troops", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Mercenaries")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Soldiers")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Type");

                    b.ToTable("Troops", "Attacks");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Auditing.CommandExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CommandData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommandType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("ElapsedMilliseconds")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("CommandExecutions", "Auditing");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Auditing.QueryExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<double>("ElapsedMilliseconds")
                        .HasColumnType("float");

                    b.Property<string>("QueryData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("QueryExecutions", "Auditing");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Empires.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Type");

                    b.ToTable("Buildings", "Empires");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Empires.Workers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Type");

                    b.ToTable("Workers", "Empires");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Events.ScheduledTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExecutionMode")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Interval")
                        .HasColumnType("time");

                    b.Property<bool>("IsPaused")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastExecutionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionMode");

                    b.ToTable("ScheduledTasks", "Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            EventType = "WarOfEmpires.Domain.Empires.RecruitTaskTriggeredEvent, WarOfEmpires.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            ExecutionMode = 2,
                            Interval = new TimeSpan(0, 1, 0, 0, 0),
                            IsPaused = true
                        },
                        new
                        {
                            Id = 2,
                            EventType = "WarOfEmpires.Domain.Empires.TurnTaskTriggeredEvent, WarOfEmpires.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            ExecutionMode = 2,
                            Interval = new TimeSpan(0, 0, 10, 0, 0),
                            IsPaused = true
                        },
                        new
                        {
                            Id = 3,
                            EventType = "WarOfEmpires.Domain.Empires.BankTurnTaskTriggeredEvent, WarOfEmpires.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            ExecutionMode = 2,
                            Interval = new TimeSpan(0, 4, 0, 0, 0),
                            IsPaused = true
                        },
                        new
                        {
                            Id = 4,
                            EventType = "WarOfEmpires.Domain.Empires.UpdateRankTaskTriggeredEvent, WarOfEmpires.Domain, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
                            ExecutionMode = 1,
                            Interval = new TimeSpan(0, 0, 1, 0, 0),
                            IsPaused = true
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Game.GameStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentGrandOverlordId")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CurrentGrandOverlordId");

                    b.HasIndex("Phase");

                    b.ToTable("GameStatus", "Game");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Phase = 0
                        });
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Markets.Caravan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Caravans", "Markets");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Markets.Merchandise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CaravanId")
                        .HasColumnType("int");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CaravanId");

                    b.HasIndex("Type");

                    b.ToTable("Merchandise", "Markets");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Markets.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BuyerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("SellerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuyerId");

                    b.HasIndex("SellerId");

                    b.HasIndex("Type");

                    b.ToTable("Transactions", "Markets");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Players.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<int>("RecipientId")
                        .HasColumnType("int");

                    b.Property<int>("SenderId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages", "Players");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Players.Player", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AllianceId")
                        .HasColumnType("int");

                    b.Property<int?>("AllianceRoleId")
                        .HasColumnType("int");

                    b.Property<int>("AttackTurns")
                        .HasColumnType("int");

                    b.Property<int>("BankTurns")
                        .HasColumnType("int");

                    b.Property<int>("CurrentRecruitingEffort")
                        .HasColumnType("int");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<long>("GrandOverlordTime")
                        .HasColumnType("bigint");

                    b.Property<bool>("HasNewChatMessages")
                        .HasColumnType("bit");

                    b.Property<bool>("HasNewMarketSales")
                        .HasColumnType("bit");

                    b.Property<bool>("HasUpkeepRunOut")
                        .HasColumnType("bit");

                    b.Property<int>("Peasants")
                        .HasColumnType("int");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Stamina")
                        .HasColumnType("int");

                    b.Property<int>("Tax")
                        .HasColumnType("int");

                    b.Property<int>("Title")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AllianceId");

                    b.HasIndex("AllianceRoleId");

                    b.HasIndex("Title");

                    b.ToTable("Players", "Players");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Players.PlayerBlock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BlockedPlayerId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BlockedPlayerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerBlocks", "Players");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Security.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ActivationCode")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastOnline")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewEmail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("NewEmailConfirmationCode")
                        .HasColumnType("int");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Users", "Security");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Security.UserEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Type");

                    b.HasIndex("UserId");

                    b.ToTable("UserEvents", "Security");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Siege.SiegeWeapon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("Type");

                    b.ToTable("SiegeWeapons", "Siege");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Assault", b =>
                {
                    b.HasBaseType("WarOfEmpires.Domain.Attacks.Attack");

                    b.HasDiscriminator().HasValue("Assault");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.GrandOverlordAttack", b =>
                {
                    b.HasBaseType("WarOfEmpires.Domain.Attacks.Attack");

                    b.HasDiscriminator().HasValue("GrandOverlordAttack");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Raid", b =>
                {
                    b.HasBaseType("WarOfEmpires.Domain.Attacks.Attack");

                    b.HasDiscriminator().HasValue("Raid");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Revenge", b =>
                {
                    b.HasBaseType("WarOfEmpires.Domain.Attacks.Attack");

                    b.HasDiscriminator().HasValue("Revenge");
                });

            modelBuilder.Entity("AllianceNonAggressionPacts", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Alliances.Alliance", null)
                        .WithMany()
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Alliances.NonAggressionPact", null)
                        .WithMany()
                        .HasForeignKey("NonAggressionPactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AllianceWars", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Alliances.Alliance", null)
                        .WithMany()
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Alliances.War", null)
                        .WithMany()
                        .HasForeignKey("WarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PeaceDeclarations", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Alliances.Alliance", null)
                        .WithMany()
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Alliances.War", null)
                        .WithMany()
                        .HasForeignKey("WarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.Alliance", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", "Leader")
                        .WithMany()
                        .HasForeignKey("LeaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leader");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.ChatMessage", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Alliances.Alliance", null)
                        .WithMany("ChatMessages")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Players.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.Invite", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Alliances.Alliance", "Alliance")
                        .WithMany("Invites")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Players.Player", "Player")
                        .WithMany("Invites")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Alliance");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.NonAggressionPactRequest", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Alliances.Alliance", "Recipient")
                        .WithMany("ReceivedNonAggressionPactRequests")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Alliances.Alliance", "Sender")
                        .WithMany("SentNonAggressionPactRequests")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.Role", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Alliances.Alliance", "Alliance")
                        .WithMany("Roles")
                        .HasForeignKey("AllianceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Alliance");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Attack", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", "Attacker")
                        .WithMany("ExecutedAttacks")
                        .HasForeignKey("AttackerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Players.Player", "Defender")
                        .WithMany("ReceivedAttacks")
                        .HasForeignKey("DefenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.AttackResultEntity", null)
                        .WithMany("Attacks")
                        .HasForeignKey("Result")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.AttackTypeEntity", null)
                        .WithMany("Attacks")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WarOfEmpires.Domain.Common.Resources", "Resources", b1 =>
                        {
                            b1.Property<int>("AttackId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<long>("Food")
                                .HasColumnType("bigint")
                                .HasColumnName("Food");

                            b1.Property<long>("Gold")
                                .HasColumnType("bigint")
                                .HasColumnName("Gold");

                            b1.Property<long>("Ore")
                                .HasColumnType("bigint")
                                .HasColumnName("Ore");

                            b1.Property<long>("Stone")
                                .HasColumnType("bigint")
                                .HasColumnName("Stone");

                            b1.Property<long>("Wood")
                                .HasColumnType("bigint")
                                .HasColumnName("Wood");

                            b1.HasKey("AttackId");

                            b1.ToTable("Attacks");

                            b1.WithOwner()
                                .HasForeignKey("AttackId");
                        });

                    b.Navigation("Attacker");

                    b.Navigation("Defender");

                    b.Navigation("Resources")
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.AttackRound", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Attacks.Attack", null)
                        .WithMany("Rounds")
                        .HasForeignKey("AttackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.TroopTypeEntity", null)
                        .WithMany("AttackRounds")
                        .HasForeignKey("TroopType")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Casualties", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Attacks.AttackRound", null)
                        .WithMany("Casualties")
                        .HasForeignKey("AttackRoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.TroopTypeEntity", null)
                        .WithMany("Casualties")
                        .HasForeignKey("TroopType")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Troops", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", null)
                        .WithMany("Troops")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.TroopTypeEntity", null)
                        .WithMany("Troops")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Empires.Building", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", null)
                        .WithMany("Buildings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.BuildingTypeEntity", null)
                        .WithMany("Buildings")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Empires.Workers", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", null)
                        .WithMany("Workers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.WorkerTypeEntity", null)
                        .WithMany("Workers")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Events.ScheduledTask", b =>
                {
                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.TaskExecutionModeEntity", null)
                        .WithMany("ScheduledTasks")
                        .HasForeignKey("ExecutionMode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Game.GameStatus", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", "CurrentGrandOverlord")
                        .WithMany()
                        .HasForeignKey("CurrentGrandOverlordId");

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.GamePhaseEntity", null)
                        .WithMany("GameStatus")
                        .HasForeignKey("Phase")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentGrandOverlord");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Markets.Caravan", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", "Player")
                        .WithMany("Caravans")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Markets.Merchandise", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Markets.Caravan", null)
                        .WithMany("Merchandise")
                        .HasForeignKey("CaravanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.MerchandiseTypeEntity", null)
                        .WithMany("Merchandise")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Markets.Transaction", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", null)
                        .WithMany("BuyTransactions")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Players.Player", null)
                        .WithMany("SellTransactions")
                        .HasForeignKey("SellerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.MerchandiseTypeEntity", null)
                        .WithMany("Transactions")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Players.Message", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", "Recipient")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Players.Player", "Sender")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Players.Player", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Alliances.Alliance", "Alliance")
                        .WithMany("Members")
                        .HasForeignKey("AllianceId");

                    b.HasOne("WarOfEmpires.Domain.Alliances.Role", "AllianceRole")
                        .WithMany("Players")
                        .HasForeignKey("AllianceRoleId");

                    b.HasOne("WarOfEmpires.Domain.Security.User", "User")
                        .WithOne()
                        .HasForeignKey("WarOfEmpires.Domain.Players.Player", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.TitleTypeEntity", null)
                        .WithMany("Players")
                        .HasForeignKey("Title")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WarOfEmpires.Domain.Common.Resources", "BankedResources", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("int");

                            b1.Property<long>("Food")
                                .HasColumnType("bigint")
                                .HasColumnName("BankedFood");

                            b1.Property<long>("Gold")
                                .HasColumnType("bigint")
                                .HasColumnName("BankedGold");

                            b1.Property<long>("Ore")
                                .HasColumnType("bigint")
                                .HasColumnName("BankedOre");

                            b1.Property<long>("Stone")
                                .HasColumnType("bigint")
                                .HasColumnName("BankedStone");

                            b1.Property<long>("Wood")
                                .HasColumnType("bigint")
                                .HasColumnName("BankedWood");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.OwnsOne("WarOfEmpires.Domain.Common.Resources", "Resources", b1 =>
                        {
                            b1.Property<int>("PlayerId")
                                .HasColumnType("int");

                            b1.Property<long>("Food")
                                .HasColumnType("bigint")
                                .HasColumnName("Food");

                            b1.Property<long>("Gold")
                                .HasColumnType("bigint")
                                .HasColumnName("Gold");

                            b1.Property<long>("Ore")
                                .HasColumnType("bigint")
                                .HasColumnName("Ore");

                            b1.Property<long>("Stone")
                                .HasColumnType("bigint")
                                .HasColumnName("Stone");

                            b1.Property<long>("Wood")
                                .HasColumnType("bigint")
                                .HasColumnName("Wood");

                            b1.HasKey("PlayerId");

                            b1.ToTable("Players");

                            b1.WithOwner()
                                .HasForeignKey("PlayerId");
                        });

                    b.Navigation("Alliance");

                    b.Navigation("AllianceRole");

                    b.Navigation("BankedResources")
                        .IsRequired();

                    b.Navigation("Resources")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Players.PlayerBlock", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", "BlockedPlayer")
                        .WithMany()
                        .HasForeignKey("BlockedPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Players.Player", null)
                        .WithMany("PlayerBlocks")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BlockedPlayer");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Security.User", b =>
                {
                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.UserStatusEntity", null)
                        .WithMany("Users")
                        .HasForeignKey("Status")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("WarOfEmpires.Domain.Security.Password", "Password", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varbinary(20)")
                                .HasColumnName("PasswordHash");

                            b1.Property<int?>("HashIterations")
                                .IsRequired()
                                .HasColumnType("int")
                                .HasColumnName("PasswordHashIterations");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varbinary(20)")
                                .HasColumnName("PasswordSalt");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.OwnsOne("WarOfEmpires.Domain.Security.TemporaryPassword", "PasswordResetToken", b1 =>
                        {
                            b1.Property<int>("UserId")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int")
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<DateTime?>("ExpiryDate")
                                .IsRequired()
                                .HasColumnType("datetime2")
                                .HasColumnName("PasswordResetTokenExpiryDate");

                            b1.Property<byte[]>("Hash")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varbinary(20)")
                                .HasColumnName("PasswordResetTokenHash");

                            b1.Property<int?>("HashIterations")
                                .IsRequired()
                                .HasColumnType("int")
                                .HasColumnName("PasswordResetTokenHashIterations");

                            b1.Property<byte[]>("Salt")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("varbinary(20)")
                                .HasColumnName("PasswordResetTokenSalt");

                            b1.HasKey("UserId");

                            b1.ToTable("Users");

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Password")
                        .IsRequired();

                    b.Navigation("PasswordResetToken");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Security.UserEvent", b =>
                {
                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.UserEventTypeEntity", null)
                        .WithMany("UserEvents")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Domain.Security.User", "User")
                        .WithMany("UserEvents")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Siege.SiegeWeapon", b =>
                {
                    b.HasOne("WarOfEmpires.Domain.Players.Player", null)
                        .WithMany("SiegeWeapons")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WarOfEmpires.Database.ReferenceEntities.SiegeWeaponTypeEntity", null)
                        .WithMany("SiegeWeapons")
                        .HasForeignKey("Type")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.AttackResultEntity", b =>
                {
                    b.Navigation("Attacks");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.AttackTypeEntity", b =>
                {
                    b.Navigation("Attacks");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.BuildingTypeEntity", b =>
                {
                    b.Navigation("Buildings");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.GamePhaseEntity", b =>
                {
                    b.Navigation("GameStatus");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.MerchandiseTypeEntity", b =>
                {
                    b.Navigation("Merchandise");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.SiegeWeaponTypeEntity", b =>
                {
                    b.Navigation("SiegeWeapons");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.TaskExecutionModeEntity", b =>
                {
                    b.Navigation("ScheduledTasks");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.TitleTypeEntity", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.TroopTypeEntity", b =>
                {
                    b.Navigation("AttackRounds");

                    b.Navigation("Casualties");

                    b.Navigation("Troops");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.UserEventTypeEntity", b =>
                {
                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.UserStatusEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("WarOfEmpires.Database.ReferenceEntities.WorkerTypeEntity", b =>
                {
                    b.Navigation("Workers");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.Alliance", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("Invites");

                    b.Navigation("Members");

                    b.Navigation("ReceivedNonAggressionPactRequests");

                    b.Navigation("Roles");

                    b.Navigation("SentNonAggressionPactRequests");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Alliances.Role", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.Attack", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Attacks.AttackRound", b =>
                {
                    b.Navigation("Casualties");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Markets.Caravan", b =>
                {
                    b.Navigation("Merchandise");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Players.Player", b =>
                {
                    b.Navigation("Buildings");

                    b.Navigation("BuyTransactions");

                    b.Navigation("Caravans");

                    b.Navigation("ExecutedAttacks");

                    b.Navigation("Invites");

                    b.Navigation("PlayerBlocks");

                    b.Navigation("ReceivedAttacks");

                    b.Navigation("ReceivedMessages");

                    b.Navigation("SellTransactions");

                    b.Navigation("SentMessages");

                    b.Navigation("SiegeWeapons");

                    b.Navigation("Troops");

                    b.Navigation("Workers");
                });

            modelBuilder.Entity("WarOfEmpires.Domain.Security.User", b =>
                {
                    b.Navigation("UserEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
